apiVersion: v1
kind: Secret
metadata:
  name: my-pvt-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
    type: git 
    url: https://github.com/varukoluaravind22/kubernetes-yaml.git
    username: my-https-repo
    password: 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

