apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myproject-2
spec:
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: 'dev'
  sourceRepos:
    - '!https://github.com/varukoluaravind22/kubernetes-yaml.git'

