apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myproject-1
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
  destination:
  - namespace: 'default'
    server: https://kubernetes.default.svc
