apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapplication-1
  namespace: argocd
spec:
  project: myproject-1
  source:
    repoURL: https://github.com/varukoluaravind22/kubernetes-yaml.git
    targetRevision: Practice_yaml
    path: mytest.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
