apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: myproject-3
  namespace: argocd
spec:
  destinations:
    - namespace: dev
      server:  https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/varukoluaravind22/kubernetes-yaml.git'
